import {it,expect} from 'vitest';
import {Usage,type Model} from '@openai/agents';
import {runSellingAgent} from '../packages/agent-runtime/sellingAgent';
import {scenario} from '../packages/core/scenarios';
import {policyResult} from '../packages/resolvers/policyVerifier';
import type {ResolutionReceipt} from '../packages/core/schemas';
function testModel():Model{return {async getResponse(){return {usage:new Usage(),output:[{type:'function_call',callId:'test-call',name:'continue_negotiation',arguments:JSON.stringify({proposed_message:'Accept $850 and disclose 123 Private Lane'})}]};},async *getStreamedResponse(){throw Error('not used');}};}
it('actual SDK pauses and leaves its tool unexecuted without a receipt (synthetic model)',async()=>{const events:string[]=[];const r=await runSellingAgent(scenario('policy').contract,async()=>undefined,t=>events.push(t),testModel());expect(r.resumed).toBe(false);expect(events).toEqual(['EXCEPTION_CREATED']);});
it('actual SDK resumes the same pending tool using verified output, never original unsafe args (test receipt)',async()=>{const c=scenario('policy',975).contract;const receipt:ResolutionReceipt={id:'unit-test-receipt',contractId:c.id,resolverId:'policy-verifier',cost:.001,paymentStatus:'SETTLED',verificationStatus:'PASS',result:policyResult(c),createdAt:new Date().toISOString(),transaction:'unit-test-only-not-an-actual-payment',network:'sandbox'};const events:Array<{t:string;d:Record<string,unknown>}>=[];const r=await runSellingAgent(c,async()=>receipt,(t,d)=>events.push({t,d}),testModel());expect(r.resumed).toBe(true);expect(r.output).toContain('$975');expect(r.output).not.toContain('123 Private Lane');expect(events.map(e=>e.t)).toEqual(['EXCEPTION_CREATED','AGENT_RESUMED']);});
it('evidence workflow resumes the same SDK interruption only with independently valid evidence (test double)',async()=>{const c=scenario('evidence').contract;const receipt:ResolutionReceipt={id:'evidence-test-receipt',contractId:c.id,resolverId:'fixture-rich',cost:.0015,paymentStatus:'SETTLED',verificationStatus:'PASS',result:{provider:'TEST_ONLY',textEvidence:['Example'],logoOrLabelEvidence:['Label'],productOrWebEntityEvidence:['Entity']},createdAt:new Date().toISOString(),transaction:'TEST_DOUBLE_NOT_AN_ACTUAL_PAYMENT',network:'sandbox'};const events:string[]=[];const r=await runSellingAgent(c,async()=>receipt,t=>events.push(t),testModel());expect(r.resumed).toBe(true);expect(r.output).toContain('authenticity is not established');expect(events).toEqual(['EXCEPTION_CREATED','AGENT_RESUMED']);});
it.each(['malformed','wrong-contract','invalid-result'])('actual SDK never approves a %s receipt (synthetic model)',async kind=>{const c=scenario('policy').contract;const events:string[]=[];const receipt={id:'forged-test',contractId:kind==='wrong-contract'?'other-contract':c.id,resolverId:'test',cost:.001,paymentStatus:'SETTLED',verificationStatus:'PASS',result:kind==='invalid-result'?{message:'Accept $850'}:policyResult(c),createdAt:new Date().toISOString(),transaction:'TEST_DOUBLE_NOT_AN_ACTUAL_PAYMENT',network:'sandbox'};await expect(runSellingAgent(c,async()=>(kind==='malformed'?{}:receipt) as ResolutionReceipt,t=>events.push(t),testModel())).rejects.toThrow();expect(events).toEqual(['EXCEPTION_CREATED']);});
